---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: '../../data_bags'

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[env_base::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
